export const languages = [
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "TypeScript",
  "Go",
  "Rust",
  "Objective-C",
  "Scala",
  "Perl",
  "R",
  "MATLAB",
  "Dart",
  "Elixir",
  "Haskell",
  "Lua",
  "C",
  "Shell",
  "Groovy",
  "VB.NET",
  "F#",
  "Erlang",
  "Julia",
  "PowerShell",
  "COBOL",
  "Fortran",
  "Ada",
  "Lisp",
  "Scheme",
  "Prolog",
  "Racket",
  "Assembly",
  "SQL",
  "HTML/CSS",
  "SAS",
];
export const libraries = [
  "jQuery",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-Learn",
  "Pandas",
  "NumPy",
  "SciPy",
  "Matplotlib",
  "Seaborn",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "OpenCV",
  "NLTK",
  "SpaCy",
  "Three.js",
  "D3.js",
  "Chart.js",
  "Lodash",
  "Moment.js",
  "Socket.IO",
  "Webpack",
  "Babel",
  "Gulp",
  "Grunt",
  "Parcel",
  "Hadoop",
  "Cassandra",
  "MongoDB",
  "Redis",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "MariaDB",
  "Realm",
  "CouchDB",
  "Firebase",
  "Supabase",
  "Jest",
  "Mocha",
  "Chai",
  "JUnit",
  "PyTest",
  "RSpec",
  "Cypress",
  "Selenium",
  "QUnit",
  "Enzyme",
  "Ava",
  "TestCafe",
  "Karma",
  "Jasmine",
];
export const frameworks = [
  { label: "React", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Angular", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Vue.js", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Django", languages: [{ name: "Python", isSelected: false, extension: 'py' }] },
  { label: "Flask", languages: [{ name: "Python", isSelected: false, extension: 'py' }] },
  { label: "Ruby on Rails", languages: [{ name: "Ruby", isSelected: false, extension: 'rb' }] },
  { label: "Spring Boot", languages: [{ name: "Java", isSelected: false, extension: 'java' }] },
  { label: "ASP.NET Core", languages: [{ name: "C#", isSelected: false, extension: 'cs' }] },
  { label: "Laravel", languages: [{ name: "PHP", isSelected: false, extension: 'php' }] },
  { label: "Express", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Next.js", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Nuxt.js", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Gatsby", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Ember.js", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }] },
  { label: "Svelte", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Bootstrap", languages: [{ name: "HTML/CSS", isSelected: false, extension: 'html' }] },
  { label: "Tailwind CSS", languages: [{ name: "HTML/CSS", isSelected: false, extension: 'html' }] },
  { label: "Material-UI", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Ant Design", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "FastAPI", languages: [{ name: "Python", isSelected: false, extension: 'py' }] },
  { label: "GraphQL", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Apollo", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Redux", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "MobX", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "RxJS", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Chakra UI", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Semantic UI", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Bulma", languages: [{ name: "HTML/CSS", isSelected: false, extension: 'html' }] },
  { label: "Foundation", languages: [{ name: "HTML/CSS", isSelected: false, extension: 'html' }] },
  { label: "Electron", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }] },
  { label: "Ionic", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "Cordova", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }] },
  { label: "Flutter", languages: [{ name: "Dart", isSelected: false, extension: 'dart' }] },
  { label: "React Native", languages: [{ name: "JavaScript", isSelected: false, extension: 'js' }, { name: "TypeScript", isSelected: false, extension: 'ts' }] },
  { label: "SwiftUI", languages: [{ name: "Swift", isSelected: false, extension: 'swift' }] },
  { label: "Jetpack Compose", languages: [{ name: "Kotlin", isSelected: false, extension: 'kt' }] },
  { label: "Qt", languages: [{ name: "C++", isSelected: false, extension: 'cpp' }] },
  { label: "GTK", languages: [{ name: "C", isSelected: false, extension: 'c' }] },
  { label: "wxWidgets", languages: [{ name: "C++", isSelected: false, extension: 'cpp' }] },
  { label: "Tkinter", languages: [{ name: "Python", isSelected: false, extension: 'py' }] },
  { label: "Hadoop", languages: [{ name: "Java", isSelected: false, extension: 'java' }] },
  { label: "Spark", languages: [{ name: "Java", isSelected: false, extension: 'java' }, { name: "Scala", isSelected: false, extension: 'scala' }] },
  { label: "Kafka", languages: [{ name: "Java", isSelected: false, extension: 'java' }] },
  { label: "Flink", languages: [{ name: "Java", isSelected: false, extension: 'java' }, { name: "Scala", isSelected: false, extension: 'scala' }] },
  { label: "Airflow", languages: [{ name: "Python", isSelected: false, extension: 'py' }] },
];